(function(){
'use strict';
if(typeof window==='undefined'||window.__tc_novel_pack_v1__) return;
window.__tc_novel_pack_v1__=true;
var cache=null;
function S(a){var s=0;for(var i=0;i<a.length;i++)s+=a[i];return s;}
function M(a){return a.length?S(a)/a.length:NaN;}
function N(x,d){x=Number(x);return Number.isFinite(x)?x:d;}
function C(x,l,h){return Math.max(l,Math.min(h,x));}
function NCDF(x){if(typeof window.normalCDF==='function')return window.normalCDF(x);var a1=0.254829592,a2=-0.284496736,a3=1.421413741,a4=-1.453152027,a5=1.061405429,p=0.3275911,sg=x<0?-1:1,ax=Math.abs(x)/Math.SQRT2,t=1/(1+p*ax),y=1-(((((a5*t+a4)*t+a3)*t+a2)*t+a1)*t*Math.exp(-ax*ax));return 0.5*(1+sg*y);} 
function NINV(p){if(typeof window.qnorm==='function')return window.qnorm(p);if(p<=0)return -Infinity;if(p>=1)return Infinity;var a=[-39.69683028665376,220.9460984245205,-275.9285104469687,138.357751867269,-30.66479806614716,2.506628277459239],b=[-54.47609879822406,161.5858368580409,-155.6989798598866,66.80131188771972,-13.28068155288572],c=[-0.007784894002430293,-0.3223964580411365,-2.400758277161838,-2.549732539343734,4.374664141464968,2.938163982698783],d=[0.007784695709041462,0.3224671290700398,2.445134137142996,3.754408661907416],pl=0.02425,ph=1-pl,q,r; if(p<pl){q=Math.sqrt(-2*Math.log(p));return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1);} if(p<=ph){q=p-0.5;r=q*q;return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q/(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1);} q=Math.sqrt(-2*Math.log(1-p));return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1);} 
function TCDF(x,df){if(typeof window.tCDF==='function')return window.tCDF(x,df);return NCDF(x);} 
function TQ(p,df){if(typeof window.tQuantile==='function')return window.tQuantile(p,df);if(typeof window.qt==='function')return window.qt(p,df);return NINV(p);} 
function Q(a,q){if(!a.length)return NaN;var x=a.slice().sort(function(u,v){return u-v;});var p=(x.length-1)*C(q,0,1),lo=Math.floor(p),hi=Math.ceil(p);if(lo===hi)return x[lo];var w=p-lo;return x[lo]*(1-w)+x[hi]*w;}
function R(){var u=0,v=0;while(u===0)u=Math.random();while(v===0)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);} 
function GS(k,th){k=Math.max(1e-8,k);th=Math.max(1e-8,th);if(k<1){var u=Math.random();return GS(k+1,th)*Math.pow(u,1/k);}var d=k-1/3,c=1/Math.sqrt(9*d);for(;;){var x=R(),v=1+c*x;if(v<=0)continue;v=v*v*v;var u2=Math.random();if(u2<1-0.331*x*x*x*x)return d*v*th;if(Math.log(u2)<0.5*x*x+d*(1-v+Math.log(v)))return d*v*th;}} 
function BS(a,b){var x=GS(a,1),y=GS(b,1);return x/Math.max(1e-12,x+y);} 
function SM(logw){if(!logw.length)return[];var m=Math.max.apply(null,logw),ex=logw.map(function(v){return Math.exp(v-m);}),s=S(ex);return ex.map(function(v){return v/Math.max(1e-12,s);});}
function SC(p){var u=Math.random(),c=0;for(var i=0;i<p.length;i++){c+=p[i];if(u<=c)return i;}return Math.max(0,p.length-1);} 
function toast(m,t){if(typeof window.showToast==='function')window.showToast(m,t||'info');}
function state(){return typeof window.AppState!=='undefined'?window.AppState:null;}
function studies(){var s=state();if(s&&s.results&&Array.isArray(s.results.studies)&&s.results.studies.length)return s.results.studies; if(s&&Array.isArray(s.studies)&&s.studies.length)return s.studies; return[];}
function vec(st){var yi=[],vi=[],nm=[];for(var i=0;i<st.length;i++){var r=st[i]||{},y=N(r.yi,NaN),v=N(r.vi,NaN);if(Number.isFinite(y)&&Number.isFinite(v)&&v>0){yi.push(y);vi.push(v);nm.push(r.name||('Study '+(i+1)));}}return{yi:yi,vi:vi,names:nm};}
function clusters(st,nm){var o=[];for(var i=0;i<st.length;i++){var r=st[i]||{},raw=r.cluster_id||r.study_id||r.trial_id||nm[i]||('c'+i),k=String(raw).replace(/\s*\(.*?\)\s*/g,'').trim();o.push(k||('c'+i));}return o;}
function prereg(st){var o=[];for(var i=0;i<st.length;i++){var r=st[i]||{},b=r.preregistered;if(typeof b==='boolean'){o.push(b?1:0);continue;} if(r.registration||r.registry||r.protocol_id){o.push(1);continue;} if(typeof r.year==='number'&&r.year>=2018){o.push(1);continue;} o.push(0);}return o;}
function tables(st){var o=[];for(var i=0;i<st.length;i++){var r=st[i]||{},ai=N(r.ai,NaN),bi=N(r.bi,NaN),ci=N(r.ci,NaN),di=N(r.di,NaN);if(!(ai>=0&&bi>=0&&ci>=0&&di>=0)){var et=N(r.events_t,NaN),nt=N(r.n_t,NaN),ec=N(r.events_c,NaN),nc=N(r.n_c,NaN);if(Number.isFinite(et)&&Number.isFinite(nt)&&Number.isFinite(ec)&&Number.isFinite(nc)&&nt>=et&&nc>=ec){ai=et;bi=nt-et;ci=ec;di=nc-ec;}}if(ai>=0&&bi>=0&&ci>=0&&di>=0)o.push({ai:ai,bi:bi,ci:ci,di:di,name:r.name||('Study '+(i+1))});}return o;}
function tau(yi,vi,m){if(typeof window.estimateTau2==='function'){var out=window.estimateTau2(yi,vi,m||'REML')||{};return Math.max(0,N(out.tau2,0));}var w=vi.map(function(v){return 1/v;}),sw=S(w),th=S(yi.map(function(y,i){return y*w[i];}))/Math.max(1e-12,sw),q=S(yi.map(function(y,i){var d=y-th;return w[i]*d*d;})),sw2=S(w.map(function(x){return x*x;})),c=sw-sw2/Math.max(1e-12,sw);return Math.max(0,(q-(yi.length-1))/Math.max(1e-12,c));}
function pool(yi,vi,t2){if(typeof window.calculatePooledEstimate==='function'){var o=window.calculatePooledEstimate(yi,vi,{tau2:t2},'REML')||{};return{theta:N(o.theta,NaN),se:N(o.se,NaN),lo:N(o.ci_lower,NaN),hi:N(o.ci_upper,NaN)};}var w=vi.map(function(v){return 1/(v+t2);}),sw=S(w),th=S(yi.map(function(y,i){return y*w[i];}))/Math.max(1e-12,sw),se=Math.sqrt(1/Math.max(1e-12,sw));return{theta:th,se:se,lo:th-1.96*se,hi:th+1.96*se};}
function robma(yi,vi,opt){opt=opt||{};var draws=Math.max(2000,N(opt.draws,7000)),mods=[];try{if(typeof window.fitREModel==='function'){var re=window.fitREModel(yi,vi);mods.push({name:'RE',theta:re.theta,se:Math.max(1e-8,re.se),bic:re.bic,bias:false});}}catch(_){}
try{if(typeof window.fitFEModel==='function'){var fe=window.fitFEModel(yi,vi);mods.push({name:'FE',theta:fe.theta,se:Math.max(1e-8,fe.se),bic:fe.bic,bias:false});}}catch(_){}
try{if(typeof window.fitPETModel==='function'){var sei=vi.map(Math.sqrt),pet=window.fitPETModel(yi,vi,sei);mods.push({name:'PET',theta:pet.theta,se:Math.max(1e-8,pet.se),bic:pet.bic,bias:true});}}catch(_){}
try{if(typeof window.fitPEESEModel==='function'){var sei2=vi.map(Math.sqrt),pe=window.fitPEESEModel(yi,vi,sei2);mods.push({name:'PEESE',theta:pe.theta,se:Math.max(1e-8,pe.se),bic:pe.bic,bias:true});}}catch(_){}
try{if(typeof window.fitSelectionModelRoBMA==='function'){var sei3=vi.map(Math.sqrt),sl=window.fitSelectionModelRoBMA(yi,vi,sei3);mods.push({name:'Selection',theta:sl.theta,se:Math.max(1e-8,sl.se||0.2),bic:sl.bic,bias:true});}}catch(_){}
if(!mods.length){var t2=tau(yi,vi,'REML'),re0=pool(yi,vi,t2),fe0=pool(yi,vi,0);mods.push({name:'RE-fallback',theta:re0.theta,se:Math.max(1e-8,re0.se),bic:2,bias:false});mods.push({name:'FE-fallback',theta:fe0.theta,se:Math.max(1e-8,fe0.se),bic:3,bias:false});}
var probs=SM(mods.map(function(m){return -0.5*N(m.bic,1e6);}));for(var i=0;i<mods.length;i++)mods[i].w=probs[i];
var th=new Array(draws),cnt=new Array(mods.length).fill(0);for(var d=0;d<draws;d++){var j=SC(probs),m=mods[j];cnt[j]+=1;th[d]=m.theta+m.se*R();}
return{ok:true,method:'RoBMA posterior Monte Carlo',theta:M(th),ci_lower:Q(th,0.025),ci_upper:Q(th,0.975),pBias:S(mods.filter(function(m){return m.bias;}).map(function(m){return m.w;})),draws:draws,models:mods.map(function(m,i){return{name:m.name,weight:m.w,sampled:cnt[i]};})};}
function hyema(yi,vi,pr){if(!yi.length||yi.length!==vi.length||yi.length!==pr.length) throw new Error('HYEMA requires aligned arrays');var k=yi.length,x=pr.map(function(p){return p?0:1;}),np=pr.filter(function(p){return!!p;}).length,nn=k-np;if(np<2||nn<2) return{ok:false,warning:'Need >=2 prereg and >=2 non-prereg studies',n_prereg:np,n_non:nn};
var t2=tau(yi,vi,'REML'),b0=0,b1=0;for(var it=0;it<120;it++){var w=vi.map(function(v){return 1/(v+t2);}),s00=S(w),s01=S(w.map(function(wi,i){return wi*x[i];})),s11=S(w.map(function(wi,i){return wi*x[i]*x[i];})),y0=S(w.map(function(wi,i){return wi*yi[i];})),y1=S(w.map(function(wi,i){return wi*yi[i]*x[i];})),det=s00*s11-s01*s01;if(!(det>1e-12))break;b0=(y0*s11-y1*s01)/det;b1=(y1*s00-y0*s01)/det;var r=yi.map(function(y,i){return y-b0-b1*x[i];}),sw=S(w),sw2=S(w.map(function(v){return v*v;})),c=sw-sw2/Math.max(1e-12,sw),q=S(r.map(function(rv,i){return w[i]*rv*rv;})),tn=Math.max(0,(q-(k-2))/Math.max(1e-12,c));if(Math.abs(tn-t2)<1e-9){t2=tn;break;}t2=0.5*(t2+tn);}var w2=vi.map(function(v){return 1/(v+t2);}),s00b=S(w2),s01b=S(w2.map(function(wi,i){return wi*x[i];})),s11b=S(w2.map(function(wi,i){return wi*x[i]*x[i];})),detb=Math.max(1e-12,s00b*s11b-s01b*s01b),se1=Math.sqrt(Math.max(1e-12,s00b/detb)),z=b1/se1,p=2*(1-NCDF(Math.abs(z)));return{ok:true,method:'HYEMA prereg-aware',theta_preregistered:b0,theta_non_preregistered:b0+b1,prereg_bias_shift:b1,se_shift:se1,p_shift:p,tau2:t2,n_prereg:np,n_non:nn};}
function rare(st2,opt){opt=opt||{};var draws=Math.max(1500,N(opt.draws,5000));if(!Array.isArray(st2)||st2.length<2) return{ok:false,warning:'Need >=2 binary studies'};var rows=st2.map(function(r){var ai=Math.max(0,N(r.ai,0)),bi=Math.max(0,N(r.bi,0)),ci=Math.max(0,N(r.ci,0)),di=Math.max(0,N(r.di,0)),lor=Math.log((ai+0.5)*(di+0.5)/Math.max(1e-12,(bi+0.5)*(ci+0.5))),v=1/(ai+0.5)+1/(bi+0.5)+1/(ci+0.5)+1/(di+0.5);return{ai:ai,bi:bi,ci:ci,di:di,lor:lor,vi:v};});
var base=tau(rows.map(function(r){return r.lor;}),rows.map(function(r){return r.vi;}),'REML'),th=new Array(draws);for(var d=0;d<draws;d++){var t2=Math.max(0,base+0.05*Math.abs(R())*Math.sqrt(1+base)),y=[],v=[];for(var i=0;i<rows.length;i++){var rr=rows[i],pt=BS(rr.ai+0.5,rr.bi+0.5),pc=BS(rr.ci+0.5,rr.di+0.5),lor2=Math.log(pt/Math.max(1e-12,1-pt))-Math.log(pc/Math.max(1e-12,1-pc));y.push(lor2);v.push(rr.vi);}var w=v.map(function(x){return 1/(x+t2);}),sw=S(w);th[d]=S(y.map(function(x,i){return x*w[i];}))/Math.max(1e-12,sw);}var tt=M(th),lo=Q(th,0.025),hi=Q(th,0.975),pb=M(th.map(function(x){return x<0?1:0;}));return{ok:true,method:'Rare-event exact beta-binomial',theta:tt,OR:Math.exp(tt),ci_lower:lo,ci_upper:hi,OR_ci:[Math.exp(lo),Math.exp(hi)],prob_OR_lt_1:pb,tau2_anchor:base,k:rows.length,draws:draws};}
function robustT(yi,vi,opt){opt=opt||{};var nu=C(N(opt.nu,4),2.1,40),t2=tau(yi,vi,'REML'),th=pool(yi,vi,t2).theta,wi=yi.map(function(){return 1;}),conv=false;for(var it=0;it<200;it++){var den=vi.map(function(v){return v+t2;}),res=yi.map(function(y){return y-th;}),tw=res.map(function(r,i){return (nu+1)/Math.max(1e-12,nu+(r*r)/Math.max(1e-12,den[i]));});wi=tw.map(function(w,i){return w/Math.max(1e-12,den[i]);});var sw=S(wi);th=S(yi.map(function(y,i){return y*wi[i];}))/Math.max(1e-12,sw);var r2=yi.map(function(y){return y-th;}),num=S(tw.map(function(w,i){return w*Math.max(0,r2[i]*r2[i]-vi[i]);})),de=Math.max(1e-12,S(tw)),tn=Math.max(0,num/de);if(Math.abs(tn-t2)<1e-9){t2=tn;conv=true;break;}t2=0.5*t2+0.5*tn;}var se=Math.sqrt(1/Math.max(1e-12,S(wi))),z=th/Math.max(1e-12,se);return{ok:true,method:'Robust t random effects',nu:nu,theta:th,se:se,ci_lower:th-1.96*se,ci_upper:th+1.96*se,p_value:2*(1-NCDF(Math.abs(z))),tau2:t2,converged:conv};}
function seq(yi,vi,opt){opt=opt||{};var alpha=C(N(opt.alpha,0.05),0.001,0.2),dir=String(opt.direction||((state()&&state().settings&&state().settings.direction)||'lower')),ft=tau(yi,vi,'REML'),fw=yi.map(function(_,i){return 1/(vi[i]+ft);}),fi=Math.max(1e-12,S(fw)),firstT=null,firstB=null,cum=[],pv=1,pm=0;for(var k=3;k<=yi.length;k++){var y=yi.slice(0,k),v=vi.slice(0,k),t2=tau(y,v,'REML'),po=pool(y,v,t2),z=po.theta/Math.max(1e-12,po.se),info=S(v.map(function(x){return 1/(x+t2);})),fr=C(info/fi,1e-6,1),bd=NINV(1-alpha/(2*Math.sqrt(fr))),cr=Math.abs(z)>bd;if(cr&&firstT==null)firstT={k:k,z:z,boundary:bd};var w=v.map(function(x){return 1/(x+t2);}),postVar=1/(1/pv+S(w)),postMean=postVar*(pm/pv+S(y.map(function(x,i){return x*w[i];}))),postSd=Math.sqrt(postVar),pe=dir==='lower'?NCDF((0-postMean)/postSd):1-NCDF((0-postMean)/postSd);if(pe>0.975&&firstB==null)firstB={k:k,p_effect:pe};cum.push({k:k,theta:po.theta,se:po.se,z:z,info_frac:fr,tsa_boundary:bd,tsa_crossed:cr,bayes_p_effect:pe});}return{ok:true,method:'Sequential TSA + Bayesian monitoring',alpha:alpha,first_tsa_crossing:firstT,first_bayesian_crossing:firstB,cumulative:cum};}
function egger(yi,vi,cl){var k=yi.length;if(k<6)return{ok:false,warning:'Need >=6 effects'};var sei=vi.map(Math.sqrt),x=sei.map(function(s){return 1/Math.max(1e-12,s);}),y=yi.map(function(v,i){return v/Math.max(1e-12,sei[i]);}),s00=0,s01=0,s11=0,y0=0,y1=0;for(var i=0;i<k;i++){s00+=1;s01+=x[i];s11+=x[i]*x[i];y0+=y[i];y1+=y[i]*x[i];}var det=s00*s11-s01*s01;if(!(det>1e-12))return{ok:false,warning:'Singular design'};var b0=(y0*s11-y1*s01)/det,b1=(y1*s00-y0*s01)/det,inv=[[s11/det,-s01/det],[-s01/det,s00/det]],grp={};for(i=0;i<k;i++){var key=String(cl[i]==null?i:cl[i]),u=y[i]-b0-b1*x[i];if(!grp[key])grp[key]=[0,0];grp[key][0]+=u;grp[key][1]+=u*x[i];}var keys=Object.keys(grp),m=keys.length,m00=0,m01=0,m11=0;for(i=0;i<keys.length;i++){var g=grp[keys[i]];m00+=g[0]*g[0];m01+=g[0]*g[1];m11+=g[1]*g[1];}var meat=[[m00,m01],[m01,m11]],t00=inv[0][0]*meat[0][0]+inv[0][1]*meat[1][0],t01=inv[0][0]*meat[0][1]+inv[0][1]*meat[1][1],t10=inv[1][0]*meat[0][0]+inv[1][1]*meat[1][0],t11=inv[1][0]*meat[0][1]+inv[1][1]*meat[1][1],cov00=t00*inv[0][0]+t01*inv[1][0],cov11=t10*inv[0][1]+t11*inv[1][1],corr=m>1?(m/(m-1))*((k-1)/Math.max(1,k-2)):1,se0=Math.sqrt(Math.max(1e-12,corr*cov00)),se1=Math.sqrt(Math.max(1e-12,corr*cov11)),df=Math.max(1,m-1),tt=b0/se0,p=2*(1-TCDF(Math.abs(tt),df));return{ok:true,method:'Egger-RVE',intercept:b0,se_intercept:se0,slope:b1,se_slope:se1,t_intercept:tt,df:df,p_intercept:p,clusters:m};}
function runPack(opts){var st=studies(),v=vec(st);if(v.yi.length<3)return{ok:false,error:'Run analysis first with >=3 studies'};var pr=prereg(st).slice(0,v.yi.length),cl=clusters(st,v.names).slice(0,v.yi.length),tb=tables(st),out={ok:true,generated_at:new Date().toISOString(),pack_version:'2026-03-05',k:v.yi.length,methods:{}};
try{out.methods.robma_full=robma(v.yi,v.vi,opts&&opts.robma);}catch(e){out.methods.robma_full={ok:false,error:String(e.message||e)};}
try{out.methods.hyema=hyema(v.yi,v.vi,pr);}catch(e){out.methods.hyema={ok:false,error:String(e.message||e)};}
try{out.methods.rare_event_exact=rare(tb,opts&&opts.rare_event);}catch(e){out.methods.rare_event_exact={ok:false,error:String(e.message||e)};}
try{out.methods.robust_t_re=robustT(v.yi,v.vi,opts&&opts.robust_t);}catch(e){out.methods.robust_t_re={ok:false,error:String(e.message||e)};}
try{out.methods.sequential_meta=seq(v.yi,v.vi,opts&&opts.sequential);}catch(e){out.methods.sequential_meta={ok:false,error:String(e.message||e)};}
try{out.methods.egger_rve=egger(v.yi,v.vi,cl);}catch(e){out.methods.egger_rve={ok:false,error:String(e.message||e)};}
var s=state();if(s&&s.results)s.results.novelValidatedMethods=out;cache=out;return out;}
function F(x,d){return Number.isFinite(x)?Number(x).toFixed(d==null?4:d):'NA';}
function render(res){var host=document.getElementById('tcNovelValidatedResults');if(!host)return;if(!res||!res.ok){host.innerHTML='<div class="alert alert--warning"><span class="alert__icon">!</span><div class="alert__content"><div class="alert__text">'+(res&&res.error?res.error:'Novel methods unavailable')+'</div></div></div>';return;}var m=res.methods||{},rb=m.robma_full||{},hy=m.hyema||{},re=m.rare_event_exact||{},tr=m.robust_t_re||{},sq=m.sequential_meta||{},eg=m.egger_rve||{};host.innerHTML='<div class="stat-grid" style="grid-template-columns:repeat(3,1fr);gap:var(--space-2);">'+
'<div class="stat-card"><div class="stat-card__label">RoBMA theta</div><div class="stat-card__value">'+F(rb.theta,4)+'</div></div>'+
'<div class="stat-card"><div class="stat-card__label">HYEMA shift</div><div class="stat-card__value">'+F(hy.prereg_bias_shift,4)+'</div></div>'+
'<div class="stat-card"><div class="stat-card__label">Rare-event OR</div><div class="stat-card__value">'+F(re.OR,3)+'</div></div>'+
'<div class="stat-card"><div class="stat-card__label">Robust t tau2</div><div class="stat-card__value">'+F(tr.tau2,4)+'</div></div>'+
'<div class="stat-card"><div class="stat-card__label">Seq first TSA</div><div class="stat-card__value">'+(sq.first_tsa_crossing?sq.first_tsa_crossing.k:'none')+'</div></div>'+
'<div class="stat-card"><div class="stat-card__label">Egger-RVE p</div><div class="stat-card__value">'+F(eg.p_intercept,4)+'</div></div></div>'+
'<details style="margin-top:var(--space-3);"><summary style="cursor:pointer;font-weight:600;">Method details</summary><pre style="white-space:pre-wrap;font-size:12px;max-height:300px;overflow:auto;background:var(--surface-overlay);padding:8px;border-radius:8px;">'+JSON.stringify(res,null,2)+'</pre></details>';}
function dl(name,p){var b=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(u);} 
function inject(){if(typeof document==='undefined')return;if(document.getElementById('tcNovelValidatedCard'))return;var panel=document.getElementById('panel-advanced');if(!panel)return;var host=panel.querySelector('.card .card__body')||panel,card=document.createElement('div');card.id='tcNovelValidatedCard';card.className='card';card.style.marginTop='var(--space-4)';card.innerHTML='<div class="card__header"><h3 class="card__title">Novel Validated Pairwise Methods</h3><p class="card__subtitle">RoBMA posterior MC, HYEMA prereg-aware, rare-event exact beta-binomial, robust t RE, sequential TSA, Egger-RVE</p></div><div class="card__body"><div class="flex gap-2" style="flex-wrap:wrap;"><button class="btn btn--primary btn--sm" id="tcRunNovelValidatedBtn">Run Novel Methods Pack</button><button class="btn btn--ghost btn--sm" id="tcExportNovelValidatedBtn">Export Novel Results JSON</button></div><div id="tcNovelValidatedResults" style="margin-top:var(--space-3);font-size:var(--text-sm);"><div class="alert alert--info"><span class="alert__icon">i</span><div class="alert__content"><div class="alert__text">Run analysis, then click Run Novel Methods Pack.</div></div></div></div></div>';host.appendChild(card);
var rb=document.getElementById('tcRunNovelValidatedBtn');if(rb&&!rb.__b){rb.__b=true;rb.addEventListener('click',function(){try{var out=runPack({});render(out);toast('Novel validated methods pack complete.','success');}catch(e){render({ok:false,error:String(e.message||e)});toast('Novel methods pack failed: '+String(e.message||e),'error');}});}var eb=document.getElementById('tcExportNovelValidatedBtn');if(eb&&!eb.__b){eb.__b=true;eb.addEventListener('click',function(){if(!cache){toast('Run novel methods first.','warning');return;}dl('truthcert_novel_validated_'+Date.now()+'.json',cache);toast('Novel methods results exported.','success');});}}
window.tcRoBMAFullMCMC=robma;window.tcHYEMA=hyema;window.tcRareEventExact=rare;window.tcRobustTRE=robustT;window.tcSequentialMeta=seq;window.tcEggerRVE=egger;window.runNovelValidatedPack=runPack;
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else setTimeout(inject,0);} 
})();
